// Package domain is e-Way Bill's persisted record shape (brief §10). e-Way
// Bills are generated BY IRN through the same domain.EInvoiceProvider
// interface einvoice uses (docs/architecture.md §9 groups
// GenerateEWayBillByIRN/CancelEWayBill/GetEWayBillByIRN into that one
// interface) — this package does not define a second provider interface,
// it reuses einvoice's.
package domain

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
)

type Status string

const (
	StatusDraft           Status = "DRAFT"
	StatusQueued          Status = "QUEUED"
	StatusSubmitting      Status = "SUBMITTING"
	StatusGenerated       Status = "GENERATED"
	StatusFailedRetryable Status = "FAILED_RETRYABLE"
	StatusFailedFinal     Status = "FAILED_FINAL"
	StatusCancelPending   Status = "CANCEL_PENDING"
	StatusCancelled       Status = "CANCELLED"
	// StatusClosed is distinct from StatusCancelled — the 2026-08-01 GSTN
	// change (docs/research.md): the shipment DID happen, it's just no
	// longer "in transit." A cancelled EWB means the movement never
	// happened at all. See ClosedByRole for who's allowed to do this.
	StatusClosed Status = "CLOSED"
)

func (s Status) Terminal() bool {
	switch s {
	case StatusGenerated, StatusCancelled, StatusClosed, StatusFailedFinal:
		return true
	default:
		return false
	}
}

// ClosedByRole is who performed a voluntary closure — the 2026-08-01
// advisory names exactly these four as eligible.
type ClosedByRole string

const (
	ClosedBySupplier    ClosedByRole = "SUPPLIER"
	ClosedByRecipient   ClosedByRole = "RECIPIENT"
	ClosedByTransporter ClosedByRole = "TRANSPORTER"
	ClosedByDriver      ClosedByRole = "DRIVER"
)

type PartBUpdate struct {
	At              time.Time `json:"at"`
	VehicleNumber   string    `json:"vehicle_number"`
	TransporterID   string    `json:"transporter_id,omitempty"`
	TransporterName string    `json:"transporter_name,omitempty"`
	Reason          string    `json:"reason,omitempty"`
}

type Record struct {
	ID               uuid.UUID
	OrganisationID   uuid.UUID
	SalesDocumentID  uuid.UUID
	EInvoiceRecordID *uuid.UUID
	IRN              *string
	EWBNumber        *string
	Status           Status
	ValidFrom        *time.Time
	ValidUntil       *time.Time
	// ShipToGSTIN is nullable pre-resolution; the literal "URP" is a
	// valid resolved value (unregistered/not-applicable recipient), not a
	// sentinel for "unset" — see migrations/0024's column comment.
	ShipToGSTIN     *string
	TransporterID   string
	TransporterName string
	VehicleNumber   string
	DistanceKM      *string // decimal.Decimal.String(); kept as string here to avoid a decimal import just for pass-through display
	PartBHistory    []PartBUpdate
	ClosedAt        *time.Time
	ClosedByRole    *ClosedByRole
	ErrorCode       *string
	ErrorMessage    *string
	CorrelationID   *string
	CancelledAt     *time.Time
	CancelReason    *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type UpdateFields struct {
	EWBNumber     *string
	ValidFrom     *time.Time
	ValidUntil    *time.Time
	ShipToGSTIN   *string
	ClosedAt      *time.Time
	ClosedByRole  *ClosedByRole
	ErrorCode     *string
	ErrorMessage  *string
	CorrelationID *string
	CancelledAt   *time.Time
	CancelReason  *string
}

type Repository interface {
	GetBySalesDocumentID(ctx context.Context, salesDocumentID uuid.UUID) (*Record, error)
	Create(ctx context.Context, r *Record) error
	UpdateStatus(ctx context.Context, id uuid.UUID, status Status, fields UpdateFields) error
	// AppendPartBHistory is separate from UpdateStatus because it's an
	// append (jsonb ||), not a COALESCE-if-set overwrite like every other
	// field — folding both patterns into one dynamic query invites bugs;
	// two narrow, obviously-correct queries are worth more here than one
	// clever one.
	AppendPartBHistory(ctx context.Context, id uuid.UUID, entry PartBUpdate) error
}

var (
	ErrNotFound         = errors.New("ewaybill: record not found")
	ErrNotGenerated     = errors.New("ewaybill: not GENERATED, cannot close/cancel")
	ErrInvalidCloseRole = errors.New("ewaybill: closed_by_role must be one of SUPPLIER, RECIPIENT, TRANSPORTER, DRIVER")
)
